package com.pulseguard.ui.theme

import androidx.compose.ui.graphics.Color

// --- Brand: "guardian teal" — health, monitoring, go. -----------------------

// Light
val md_primary = Color(0xFF116B5E)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFFA0F2DF)
val md_onPrimaryContainer = Color(0xFF00201A)
val md_secondary = Color(0xFF4C6359)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFCEE9DC)
val md_onSecondaryContainer = Color(0xFF092017)
val md_tertiary = Color(0xFF3D6373)
val md_onTertiary = Color(0xFFFFFFFF)
val md_tertiaryContainer = Color(0xFFC1E8FB)
val md_onTertiaryContainer = Color(0xFF001F29)
val md_background = Color(0xFFF5FBF7)
val md_onBackground = Color(0xFF171D1A)
val md_surface = Color(0xFFF5FBF7)
val md_onSurface = Color(0xFF171D1A)
val md_surfaceVariant = Color(0xFFDBE5DF)
val md_onSurfaceVariant = Color(0xFF3F4945)
val md_outline = Color(0xFF6F7975)
val md_outlineVariant = Color(0xFFBFC9C3)
val md_error = Color(0xFFBA1A1A)
val md_onError = Color(0xFFFFFFFF)
val md_errorContainer = Color(0xFFFFDAD6)
val md_onErrorContainer = Color(0xFF410002)

// Dark
val md_primary_dark = Color(0xFF84D5C2)
val md_onPrimary_dark = Color(0xFF00382E)
val md_primaryContainer_dark = Color(0xFF005143)
val md_onPrimaryContainer_dark = Color(0xFFA0F2DF)
val md_secondary_dark = Color(0xFFB2CCC0)
val md_onSecondary_dark = Color(0xFF1D352C)
val md_secondaryContainer_dark = Color(0xFF344B42)
val md_onSecondaryContainer_dark = Color(0xFFCEE9DC)
val md_tertiary_dark = Color(0xFFA5CCDF)
val md_onTertiary_dark = Color(0xFF063543)
val md_tertiaryContainer_dark = Color(0xFF244C5B)
val md_onTertiaryContainer_dark = Color(0xFFC1E8FB)
val md_background_dark = Color(0xFF0E1513)
val md_onBackground_dark = Color(0xFFDDE4DF)
val md_surface_dark = Color(0xFF0E1513)
val md_onSurface_dark = Color(0xFFDDE4DF)
val md_surfaceVariant_dark = Color(0xFF3F4945)
val md_onSurfaceVariant_dark = Color(0xFFBFC9C3)
val md_outline_dark = Color(0xFF899390)
val md_outlineVariant_dark = Color(0xFF3F4945)
val md_error_dark = Color(0xFFFFB4AB)
val md_onError_dark = Color(0xFF690005)
val md_errorContainer_dark = Color(0xFF93000A)
val md_onErrorContainer_dark = Color(0xFFFFDAD6)

// --- Semantic status colors (health traffic-lights) -------------------------
val statusOkLight = Color(0xFF1B873B)
val statusOkDark = Color(0xFF7FDF9A)
val statusWarnLight = Color(0xFFB06A00)
val statusWarnDark = Color(0xFFFFC04D)
val statusFailLight = Color(0xFFC0201A)
val statusFailDark = Color(0xFFFFB4AB)
val statusUnknownLight = Color(0xFF6F7975)
val statusUnknownDark = Color(0xFF9AA5A0)
